# Blog information
name: jilongliao.com
description: 
meta-description: "Jilong Liao's computer science blog."
url: http://jilongliao.com

# Author
author:
  name: Jilong Liao
  email: jliao2@utk.edu
  gravatar: 
  github: https://github.com/little-eyes
  500px: 
  twitter: 

include:
- .nojekyll

permalink: /:year/:title/ 
paginate: 5

destination: source/
markdown: pandoc
pandoc:
  skip: true
  flags: '--smart --mathjax --filter pandoc-citeproc'

source_url: https://github.com/little-eyes/little-eyes.github.io.git